const BlogActionTypes = {
	FETCH_POSTS_START: "FETCH_POSTS_START",
	FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
	FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
	CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
	DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
	UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",
	CREATE_COMMENT_FAILURE: "CREATE_COMMENT_FAILURE",
};

export default BlogActionTypes;
